vms_vitrine:
    resource: "@VMSVitrineBundle/resources/config/routing.yml"
    prefix :    /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

produits:
    type:     rest
    resource: VMS\VitrineBundle\Controller\ProduitController

users:
    type:     rest
    resource: VMS\VitrineBundle\Controller\UserController