vms_accueil:
    path:    /
    defaults:
        _controller:    VMSVitrineBundle:Home:index








vms_vitrine:
    path: /vitrine/{page}
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:index
        page:    1
    requirements:
       page:    \d*

vms_vitrine_vue:
    path:    /product/{id}
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:vue
    requirements:
        id:    \d+

vms_vitrine_ajouter:
    path:   /ajouter
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:ajouter

vms_vitrine_editer:
    path:    /editer/{id}
    defaults:
         _controller:    VMSVitrineBundle:Vitrine:editer
    requirements:
        id:     \d+

vms_vitrine_supprimer:
    path:    /supprimer/{id}
    defaults:
        _controller: VMSVitrineBundle:Vitrine:supprimer
    requirements:
        id:    \d+



vms_cart:
    path:    /cart
    defaults:
        _controller:    VMSVitrineBundle:Cart:cart

vms_cart_add:
    path:    /cart/add/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:add

vms_cart_change:
    path:    /cart/change/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:change

vms_cart_remove:
    path:    /cart/remove/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:remove

vms_cart_checkout:
    path:    /checkout
    defaults:
        _controller:    VMSVitrineBundle:Cart:checkout






vms_vitrine_compte:
    path:    /compte
    defaults:
        _controller:    VMSVitrineBundle:Compte:compte

vms_vitrine_historique:
    path:    /historique_achat/{page}
    defaults:
        _controller:    VMSVitrineBundle:Compte:historique
    requirements:
        page:    \d*

vms_vitrine_listeshouait:
    path: /liste_de_shouait/{page}
    defaults:
        _controller:   VMSVitrineBundle:Compte:listeShouait
    requirements:
        page:    \d*




