vms_accueil:
    path:    /
    defaults:
        _controller:    VMSVitrineBundle:Home:index



vms_vitrine:
    path: /vitrine
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:index

vms_vitrine_vue:
    path:    /product/{id}
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:vue
    requirements:
        id:    \d+

vms_vitrine_search:
    path:    /search
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:search

vms_vitrine_filters:
    path:    /filters
    defaults:
        _controller:    VMSVitrineBundle:Vitrine:filters

vms_cart:
    path:    /cart
    defaults:
        _controller:    VMSVitrineBundle:Cart:cart

vms_cart_add:
    path:    /cart/add/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:add

vms_cart_change:
    path:    /cart/change/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:change

vms_cart_remove:
    path:    /cart/remove/{id}
    defaults:
        _controller:    VMSVitrineBundle:Cart:remove

vms_cart_address:
    path:    /address
    defaults:
          _controller:    VMSVitrineBundle:Cart:address

vms_cart_checkout:
    path:    /checkout
    defaults:
        _controller:    VMSVitrineBundle:Cart:checkout






vms_vitrine_compte:
    path:    /compte
    defaults:
        _controller:    VMSVitrineBundle:Compte:compte

vms_vitrine_historique:
    path:    /historique_achat/{page}
    defaults:
        _controller:    VMSVitrineBundle:Compte:historique
    requirements:
        page:    \d*

vms_vitrine_listeshouait:
    path: /liste_de_shouait/{page}
    defaults:
        _controller:   VMSVitrineBundle:Compte:listeShouait
    requirements:
        page:    \d*




